source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMSProfileImagePicker_Example', :exclusive => true do
  pod 'MMSProfileImagePicker', :path => '../'
end

target 'MMSProfileImagePicker_Tests', :exclusive => true do
  pod 'MMSProfileImagePicker', :path => '../'

  pod 'FBSnapshotTestCase'
end
