source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMSProfileImagePicker_Example' do
  pod 'MMSProfileImagePicker', :path => '../'
end

target 'MMSProfileImagePicker_Tests' do
  pod 'MMSProfileImagePicker', :path => '../'

  pod 'FBSnapshotTestCase'
end
